### ISSUE TITLE
Implementation of GenericManager doesn't handle several exceptions

### ISSUE THREAD

**Issue by JorgeA1206** [bancolombia/secrets-manager#30]
Reviewing the code I found that the getSecret override on **AWSSecretManagerConnector** class not include its call in the try statement knowing that metod can return a exception.

![image](https://user-images.githubusercontent.com/28572704/194172717-56aacf6e-f549-4210-8279-715a7b1d9c79.png)
![image](https://user-images.githubusercontent.com/28572704/194177848-b91d3442-8e49-4a1f-ad0c-694070e7d42b.png)
![image](https://user-images.githubusercontent.com/28572704/194172764-ecf4382c-4149-4c1f-80b6-217656df38d3.png)

I wanna know if it's correct because when a **non-existent secret** is querying the library doesn't handle the exception ResourceNotFoundException.

![image](https://user-images.githubusercontent.com/28572704/194173243-1271ce45-850d-4ad1-a7e2-bd409cd84406.png)

Thank you.

**Comment by santitigaga** [comment]
Hello @JorgeA1206  thanks for the report, I agree with you. 

In this case this excepcion will can generate before map to the expected exception. 
![image](https://user-images.githubusercontent.com/12372370/194419539-e9336535-49c2-4bb2-80fe-b0958fcebffc.png)

maybe you can fix that in the sync and async version?

**Comment by JorgeA1206** [comment]
Thanks for your reply. Of course!! I will fix it!
